### ISSUE TITLE
Change naming of methods "majority" and "consensus"

### ISSUE THREAD

**Issue by alexhbnr** [bodkan/bam-caller#2]
After not having looked at the script for a while, the difference between majority or consensus calling a genotype was not intuitive and I had to check the source code to distinguish the two. Maybe we should elaborate in the README/help what each does or use different naming scheme.

**Comment by bodkan** [comment]
Thanks for the comment and for your patience with my taking so long to fix this ugly hack. :)

I implemented this in: https://github.com/bodkan/bam-caller/commit/1335ad2b46922201b021321540f1c02b5b6af53f. Unified both options under a single `--strategy majority` switch with an optional `--proportion` argument (values [0.5, 1.0]). Simple majority calling now uses the default `--proportion 0.5` value, strict consensus is implemented using `--strategy majority --proportion 1.0`, etc.

Let me know what you think.

**Comment by bodkan** [comment]
The default behaviour of majority allele sampling is to flip a coin if there are two alleles present in equal proportions to handle true perfect heterozygotes (from simulations, for example) correctly. Maybe this is too theoretical of a point, but it can be easily changed by setting the proportion to some number slightly larger than 0.5 if someone doesn't like this.

**Comment by alexhbnr** [comment]
I think it is solved very elegantly with a minimal amount of code. Well done! I leave the pleasure to close it to you.

**Comment by bodkan** [comment]
👍
