### ISSUE TITLE
genotype info

### ISSUE THREAD

**Issue by mano1988** [bodkan/bam-caller#6]
Hi Martin

Thank you for this simple pseudo genotype calling tool. I am trying confirm if I understand correctly the following.
I used random calling strategy and generated Genotypes. I am trying understand 10th column for example:
22	2251179460	.	C	.	.	.	.	GT:DP	0:1
22	51179474	.	T	.	.	.	.	GT:DP	0:1
22	51179970	.	T	.	.	.	.	GT:DP	0:1
22	51179984	.	T	.	.	.	.	GT:DP	0:1
22	51182969	.	A	G	.	.	.	GT:DP	1:1

Since VCF genotype merging needs 0/0 or 0/1 or 1/1 format.
Here do I have to convert GT: 1 into 1/1 and GT: 0 into 0/0? If so would that be correct for this tool?

Thanks
Manoharan

**Comment by bodkan** [comment]
Hi Manoharan,

> Since VCF genotype merging needs 0/0 or 0/1 or 1/1 format. [...]

Why do you think this is the case? I'm routinely merging VCF files with different ploidy states (_i.e._ merging high-coverage diploid genotype panels with low coverage random-allele-called pseudohaploid calls)? Do you use a VCF merging tool that gives you error when you try to do this?

As a side note, if you look at VCF files with X chromosome calls (1000 Genomes Project data or any other source), you find a mixture of diploid and haploid genotypes (coming from females and males, of course). So it's of course OK and even expected to see this in a VCF file.

> Here do I have to convert GT: 1 into 1/1 and GT: 0 into 0/0? If so would that be correct for this tool?

This depends on what you want to do. If you want to treat the pseudohaploid samples as if they were homozygous, then it's OK. This is, for example, what's often done for ADMIXTOOLS analyses - there you treat both states (0 and 1) as homozygous (so converting them to 2 or 0 states, respectively).

**Comment by mano1988** [comment]
Hi Martin,

Thanks for your explanations,

Why do you think this is the case? I'm routinely merging VCF files with different ploidy states (i.e. merging high-coverage diploid genotype panels with low coverage random-allele-called pseudohaploid calls)? 
I am new to low coverage pseudohaploid calling. I kind of assumed this is the case. I thought we can not mix diploid and haploid genotypes for autosomal SNP analysis such as pca, Admixture, and D-stats. 

Do you use a VCF merging tool that gives you error when you try to do this? No I merged using a perl script.
Mainly I wanted this for Admixtools projected PCA, Admixture, and D-stats. 

For admixture analysis, can we use without converting to homozygous SNPs?

Thanks again,
Manoharan

**Comment by bodkan** [comment]
> For admixture analysis, can we use without converting to homozygous SNPs?

For any analysis, I generally recommend looking up studies that used the same method you want to use and reading the corresponding method section about the specifics on genotype calling, data filtering, etc... I should not be providing general advice as there are many methods one could use to investigate admixture signals. If you want to do Admixtools analyses etc, I recommend the paper by Patterson et al., "Ancient admixture in human history".

Good luck!

(I will close this issue now, as the Github issue tracker is for reporting bugs and problems with the software. Feel free to open another issue if you encounter a bug.)
